# L_9: NumPy Basics

Introduction to numpy:

Package for scientific computing with Python

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built. Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.

The key features of numpy are:

-ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient. There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).

-Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.

-Vectorization: enables numeric operations on ndarrays.

-Input/Output: simplifies reading and writing of data from/to file.

-Additional Recommended Resources:

Numpy Documentation

Python for Data Analysis by Wes McKinney

Python Data science Handbook by Jake VanderPlas



In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3])
print(arr)

In [ ]:
print("Shape:", arr.shape)
print("Mean:", arr.mean())

In [ ]:
arr2 = np.arange(10).reshape(2, 5)
print(arr2)

1. Creating one dimensional array

In [ ]:
a = [1,2,3,4,5]
array1 = np.array(a)
array1

In [ ]:
# Create an array of evenly spaced values 
array1 = np.linspace(1,10,4)
array1

In [ ]:
array1.size

Creating two dimensional array

In [ ]:
a = [[1,2,3,5]]
array2 = np.array(a)
array2

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
array2 = np.array(a)
array2

In [ ]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9],])
array2

In [ ]:
array2.ndim

In [ ]:
array2.shape

3. Creating null and unit array

In [ ]:
array3 = np.zeros(4)
array3

In [ ]:
array3 = np.zeros((3,4))
array3

In [ ]:
array3 = np.ones(4)
array3

In [ ]:
array4 = np.eye(3,3)
array4

diagonal function

In [ ]:
array6 = np.diag([1,2,3,4])      # giving diagonal elements in array
array6

In [ ]:
np.diag(array6)       

4. Data Type

In [ ]:
a1 = np.array([11, 12]) # Python assigns the  data type
print(a1.dtype)

In [ ]:
a2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(a2.dtype)

Changing dtype

In [ ]:
a2 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(a2.dtype)

In [ ]:
a2 = np.array([11, 21], dtype=np.float32)     # Convert an array into float dtype
print(a2.dtype)
a2

5. Inspecting array

In [ ]:
array2

In [ ]:
array2.ndim      # Number of array dimensions

In [ ]:
print(array2.shape)     # Array row and column number

In [ ]:
len(array2)      # Number of rows in array

In [ ]:
array2.size      # Number of array elements

In [ ]:
array2.dtype     # Data type of array elements

In [ ]:
array2.dtype.name   # Name of data type

6. Reshaping

In [ ]:
array7 = np.random.randint(1,10,12)
array7

In [ ]:
array7.reshape(3,4)

In [ ]:
array7.reshape(3,-1)             # -1 is unkown number of columns

7. random values

In [ ]:
#np.random.seed(195)
rand_number = np.random.normal()  
rand_number

In [ ]:
array8 = np.random.normal(size = (4))      # Creates a random normal distribution of 1 row and 4 coloumns
array8

In [ ]:
#np.random.seed(217)
array8 = np.random.normal(size = (2,3))    # Creates a random normal distribution of 2 rows and 3 coloumns
array8

# L_9: NumPy Basics

Introduction to numpy:

Package for scientific computing with Python

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built. Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.

The key features of numpy are:

-ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient. There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).

-Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.

-Vectorization: enables numeric operations on ndarrays.

-Input/Output: simplifies reading and writing of data from/to file.

-Additional Recommended Resources:

Numpy Documentation

Python for Data Analysis by Wes McKinney

Python Data science Handbook by Jake VanderPlas



In [ ]:
import numpy as np

In [2]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
print("Shape:", arr.shape)
print("Mean:", arr.mean())

Shape: (3,)
Mean: 2.0


In [4]:
arr2 = np.arange(10).reshape(2, 5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
arr2 = np.arange(10).reshape(2, 5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Creating one dimensional array


In [6]:
a = [1,2,3,4,5]
array1 = np.array(a)
array1

array([1, 2, 3, 4, 5])

In [7]:
# Create an array of evenly spaced values 
array1 = np.linspace(1,10,4)
array1

array([ 1.,  4.,  7., 10.])

In [8]:
array1.size

4

Creating two dimensional array

In [9]:
a = [[1,2,3,5]]
array2 = np.array(a)
array2

array([[1, 2, 3, 5]])

In [10]:
a = [[1,2,3],[4,5,6],[7,8,9]]
array2 = np.array(a)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9],])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
array2.ndim

2

array2.shape

3.Creating null and unit array

In [14]:
array3 = np.zeros(4)
array3

array([0., 0., 0., 0.])

In [15]:
array3 = np.zeros((3,4))
array3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
array3 = np.ones(4)
array3

array([1., 1., 1., 1.])

In [17]:
array4 = np.eye(3,3)
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

diagonal function

In [18]:
array6 = np.diag([1,2,3,4])      # giving diagonal elements in array
array6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
np.diag(array6)    

array([1, 2, 3, 4])

4.Data Type

In [20]:
a1 = np.array([11, 12]) # Python assigns the  data type
print(a1.dtype)

int32


In [21]:
a2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(a2.dtype)

float64


Changing dtype

In [22]:
a2 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(a2.dtype)

int64


In [23]:
a2 = np.array([11, 21], dtype=np.float32)     # Convert an array into float dtype
print(a2.dtype)
a2

float32


array([11., 21.], dtype=float32)

5.Inspecting array

In [24]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array2.ndim      # Number of array dimensions

2

In [26]:
print(array2.shape)     # Array row and column number

(3, 3)


In [27]:
len(array2)      # Number of rows in array

3

In [28]:
array2.size      # Number of array elements

9

In [29]:
array2.dtype     # Data type of array elements

dtype('int32')

In [30]:
array2.dtype.name   # Name of data type

'int32'

6.Reshaping

In [31]:
array7 = np.random.randint(1,10,12)
array7

array([2, 8, 1, 7, 8, 7, 5, 7, 6, 7, 7, 1])

In [32]:
array7.reshape(3,4)

array([[2, 8, 1, 7],
       [8, 7, 5, 7],
       [6, 7, 7, 1]])

In [33]:
array7.reshape(3,-1)             # -1 is unkown number of columns

array([[2, 8, 1, 7],
       [8, 7, 5, 7],
       [6, 7, 7, 1]])

7.random values

In [34]:
#np.random.seed(195)
rand_number = np.random.normal()  
rand_number

0.8596689490737165

In [35]:
#np.random.seed(217)
array8 = np.random.normal(size = (2,3))    # Creates a random normal distribution of 2 rows and 3 coloumns
array8

array([[ 0.41576929,  0.55827979, -0.5176373 ],
       [ 0.69368917,  0.73190977,  0.34010602]])

In [36]:
array8 = np.random.normal(size = (4))      # Creates a random normal distribution of 1 row and 4 coloumns
array8

array([ 0.39328312,  0.19963298, -0.75403157, -1.92103644])

In [ ]:
#END