In [1]:
import numpy as np

### 1. Indexing and slicing of one dimensional array

In [ ]:
a = [1,2,3,4,5]              # same as in list
array1 = np.array(a)
array1

In [ ]:
print(array1[2])             # print element on 2nd index

In [ ]:
array1[2:4]                       # example of slicing

In [ ]:
array1[0:5:2]                    # example of step slicing

###   2. Indexing and slicing of two dimensional array

In [3]:
a = [[1,2,3],[4,5,6],[7,8,9]]
array2 = np.array(a)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(array2[0,1])         # print 2 from first row

In [ ]:
array2[1,:]   # Using both integer indexing & slicing generates an array of lower rank

In [ ]:
array2[1:3]                  # examples of slicing

In [ ]:
array2[:2]                   

In [ ]:
array2

In [ ]:
array2[2:]

In [ ]:
array2[:,2] 

In [ ]:
array2[1:2,2:3]  # When you modify a slice, you actually modify the array.

In [ ]:
array2

In [ ]:
array2[1:2,:]  # Slicing alone: generates an array of the same rank as an_array
               # Notice the [[ ]]   

In [ ]:
array2[1,2:3]         

In [ ]:
array2[1,-2]                 # examples of negative indexing

In [ ]:
array2[-3:-1]              # examples of negative slicing

### 3. Indexing of third dimension 

In [ ]:
array3 = np.array([   [ [1, 2, 3] , [4, 5, 6] ]   ,    [ [7, 8, 9], [10, 11, 12] ]   ])

print(array3)

In [ ]:
print(array3[1, 1, 2])

### 4. Iterating Arrays

In [3]:
array1 = np.array([1, 2, 3])            # for one dimensional array

for i in array1:
  print(i)          


1
2
3


In [5]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
for i in array2:          # for two dimensional array
  print(i)           

[1 2 3]
[4 5 6]
[7 8 9]


In [7]:
for x in array2:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9


In [8]:
for i in range(3):           
    for j in range(3): 
        print(array2[i,j],end = "   ")
        #print(i,j)
    print()    

1   2   3   
4   5   6   
7   8   9   


In [9]:

array3 = np.array([    [  [1, 2, 3], [4, 5, 6]  ] ,  [ [7, 8, 9], [10, 11, 12] ]   ])

array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
for x in array3:               # for three dimensional array
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [11]:
for x in array3:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
for i,j in np.ndenumerate(array3):
  print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


### 5.  Array Indexing for changing elements

In [13]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Create an array of indices
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])

In [15]:
print(row_indices, col_indices)

[0 1 2] [2 0 1]


In [16]:
print('Values in the array at those indices are : ',array2[row_indices,col_indices])

Values in the array at those indices are :  [3 4 8]


In [17]:
# adding 100 in above elements
array2[row_indices, col_indices] += 100    # a = a + 100 is same  as a+=100
array2

array([[  1,   2, 103],
       [104,   5,   6],
       [  7, 108,   9]])

In [18]:
# adding 100 in all even elements
array2[array2 % 2 == 0] += 100    # a = a + 100 is same  as a+=100
array2

array([[  1, 102, 103],
       [204,   5, 106],
       [  7, 208,   9]])

### 6. Filtering array

In [19]:
array7 = np.array([1,2,3,4])

a = [True, False, True, False]

filtered_array8 = array7[a]
filtered_array8

array([1, 3])

In [20]:
b = array7 % 2 == 0
b

array([False,  True, False,  True])

In [21]:
filtered_array9 = array7[b]
filtered_array9

array([2, 4])

### 7. Conditional slicing

In [22]:
array8 = np.arange(1,11)
array8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
array8 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
array8[array8>5]

array([ 6,  7,  8,  9, 10])

In [25]:
array8 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [26]:
array8[array8 % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [27]:
array8[array8 % 2 == 0] = 77
array8

array([ 1, 77,  3, 77,  5, 77,  7, 77,  9, 77])

### 8. Creating view and copy of array

In [4]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a = array2[1: ,1:]     # this is a view or slice (change in a, will change array2)
a                      

array([[5, 6],
       [8, 9]])

In [ ]:
array2

In [7]:
b = a.copy()           # copy
b

array([[5, 6],
       [8, 9]])

### 9. Operations on one dimensional array 

In [16]:
a = np.array([1,3,5])
b = np.arange(6,9)
print(a,b)

[1 3 5] [6 7 8]


In [9]:
a+2

array([3, 5, 7])

In [10]:
a*2

array([ 2,  6, 10])

In [11]:
a/2

array([0.5, 1.5, 2.5])

In [12]:
a**2

array([ 1,  9, 25])

In [30]:
a*b

array([ 6, 21, 40])

In [18]:
a == b

array([False, False, False])

In [19]:
a < 3

array([ True, False, False])

In [20]:
a[a < 3]

array([1])

In [31]:
print(a.dot(b))    # determine the inner product (dot product) of two vectors
print()
print(np.dot(a, b))

67

67


In [32]:
np.maximum(a, b)

array([6, 7, 8])

In [33]:
 array1 = np.array([1,2,3,4,5])

In [34]:
np.max(array1)

5

In [35]:
np.min(array1)

1

In [27]:
np.argmin(array1)     # min index value

0

In [28]:
np.argmax(array1)     # max index value

4

In [29]:
np.sin(array1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

### 10. Time for Operations  

In [36]:
%timeit np.sin(array1)         # For one line

2.21 µs ± 505 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [37]:
%%timeit               # For multiple lines
np.sqrt(array1)
np.sin(array1)

4.91 µs ± 646 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### 11. Operations on two dimensional array 

In [38]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(11,20).reshape(3,3)
print(x) 
print(y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [39]:
x+y

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [40]:
x*y

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [41]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [42]:
np.maximum(x, y)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [43]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [44]:
x.dot(y)       # determine the dot product of two matrices

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [45]:
np.dot(x,y)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [46]:
a

array([1, 3, 5])

In [48]:
# dot produce on an array and vector
print(x.dot(a)) 
print()
print(np.dot(x, a))

[22 49 76]

[22 49 76]


In [49]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
array9 = np.arange(1,10).reshape(3,3)

In [52]:
array9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.sum(array9)               # add all members

45

In [54]:
np.sum(array9 ,axis=0)       # columnwise sum

array([12, 15, 18])

In [55]:
np.sum(array9 ,axis=1)       # rowwise sum

array([ 6, 15, 24])

In [56]:
np.cumsum(array9)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [57]:
np.max(array9)

9

In [58]:
np.max(array9,axis = 1)

array([3, 6, 9])

In [59]:
np.min(array9)

1

In [60]:
np.argmax(array9)

8

In [61]:
array9.mean() # compute the mean for all elements

5.0

In [62]:
array9.mean(axis=0)

array([4., 5., 6.])

In [63]:
array9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.random.shuffle(array9)
array9

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [65]:
np.unique(array9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.unique(array9).size

9

In [67]:
np.unique(array9,return_index = True,return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 6, 7, 8, 3, 4, 5], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

End