In [1]:
import numpy as np

### 1. Merging data sets (stack function)

In [2]:
array10 = np.arange(1,5)
array11 = np.arange(6,10)

In [3]:
array10

array([1, 2, 3, 4])

In [4]:
array11

array([6, 7, 8, 9])

In [5]:
np.hstack((array10,array11))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [6]:
np.vstack((array10,array11))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [7]:
np.dstack((array10,array11))

array([[[1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]])

In [8]:
np.concatenate((array10, array11))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [11]:
np.concatenate([array10, array11], axis = 0)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [12]:
 np.array_split(array10, 2)

[array([1, 2]), array([3, 4])]

In [16]:
 np.array_split(array10, 3)

[array([1, 2]), array([3]), array([4])]

### 2. Indexing using where()

In [17]:
array13 = np.array([1,3,2,3,4,3])
a = np.where(array13 == 3)        # find index of elements
a

(array([1, 3, 5], dtype=int64),)

In [19]:
x = np.array([1,2,3,4,5])

y = np.array([11,22,33,44,55])
# where we have true in filter it will print x value and for false y value
# this is the working of .where function
filter = np.array([True, False, True, False, True])

In [20]:
out = np.where(filter, x, y)
print(out)

[ 1 22  3 44  5]


In [23]:
mat = np.random.rand(5,5)
mat

array([[0.69752251, 0.50852698, 0.91504916, 0.57636979, 0.69798932],
       [0.66701331, 0.70862449, 0.97890132, 0.85312472, 0.8890592 ],
       [0.15521504, 0.57210352, 0.80088861, 0.13259201, 0.13245083],
       [0.49335468, 0.79740374, 0.78792693, 0.51577105, 0.42826434],
       [0.46982076, 0.94489803, 0.97779706, 0.16842922, 0.81629162]])

In [24]:
np.where( mat > 0.5, 1000, -1)

array([[1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000],
       [  -1, 1000, 1000,   -1,   -1],
       [  -1, 1000, 1000, 1000,   -1],
       [  -1, 1000, 1000,   -1, 1000]])

In [ ]:
'''
if mat > 0.5:
    replace(1000)
else:
    replace(-1)'''



### 3. Use of "any" or "all" conditionals

In [25]:
arr_bools = np.array([ True, False ])

In [26]:
arr_bools.any()      # is True, if atleast one is True

True

In [27]:
arr_bools.all()      # is True, all are  True

False

In [28]:
array14 = np.array([0,1,2,3,4,5])

a = np.searchsorted(array14, [2,8,3])  # gives index of element after sorted insert

print(a)

[2 6 3]


### 4. Sorting array 

In [33]:
# create a 10 element array of randoms
raw = np.random.randint(1,10,9)

print(raw)

[1 6 9 7 1 4 1 1 3]


In [34]:
# create copy and sort
finished = np.array(raw)
finished.sort() # it will arrange values in ascending order. i.e sorting

print(finished)
print()
print(raw)

[1 1 1 1 3 4 6 7 9]

[1 6 9 7 1 4 1 1 3]


In [35]:
# inplace sorting
raw.sort() 
print(raw)

[1 1 1 1 3 4 6 7 9]


In [36]:
array14 = np.array([3, 2, 0, 1])

print(np.sort(array14))
print()
print(array14)

[0 1 2 3]

[3 2 0 1]


In [37]:
array15 = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(array15))
print()
print(array15)

[[2 3 4]
 [0 1 5]]

[[3 2 4]
 [5 0 1]]


### 5. Set Operations with np.array data type

In [38]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [39]:
np.intersect1d(s1, s2)     #common values between s1 and s2

array(['bulb', 'chair'], dtype='<U5')

In [40]:
np.union1d(s1, s2)         #common and uncommon values between s1 and 

array(['bulb', 'chair', 'desk', 'lamp'], dtype='<U5')

In [41]:
np.setdiff1d(s1, s2)       # elements in s1 that are not in s2

array(['desk'], dtype='<U5')

In [42]:
np.in1d(s1, s2)           # which element of s1 is, in s2

array([False,  True,  True])

### 6. Broadcasting

Introduction to broadcasting.
For more details, please see:
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [43]:
import numpy as np

a = np.zeros((4,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [45]:
y = a + add_rows  # add to each row of 'a' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [46]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]]) # print(add_cols) 
print(add_cols)
add_cols = add_cols.T #transpose: coverts rows into columns and vice versa

print(add_cols)

[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


In [47]:
# add to each column of 'a' using broadcasting
y = a + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [48]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(a+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
# create our 4x1 array
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [51]:
# add the two together using broadcasting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


### 7. Binary Format

In [54]:
import numpy as np
x = np.array([ 23.23, 24.24] )

In [55]:
# Save an array to a binary file in NumPy ``.npy`` format.
np.save('an_array', x,False) # saves the values in x to an_array

In [56]:
np.load('an_array.npy') 

array([23.23, 24.24])

### 8. Text Format

In [57]:
# savetxt function will store your file in text format.
np.savetxt('array2.txt', X=x, delimiter=',')

In [58]:
!type array2.txt

2.323000000000000043e+01
2.423999999999999844e+01


In [59]:
np.loadtxt('array2.txt', delimiter=',') # delimiter and sep are optional

array([23.23, 24.24])

End